KBUILD_CFLAGS += -DOPLUS_ARCH_EXTENDS

KBUILD_CFLAGS += -DOPLUS_FEATURE_AOD_RAMLESS
KBUILD_CPPFLAGS += -DOPLUS_FEATURE_AOD_RAMLESS
CFLAGS_KERNEL += -DOPLUS_FEATURE_AOD_RAMLESS
CFLAGS_MODULE += -DOPLUS_FEATURE_AOD_RAMLESS

KBUILD_CFLAGS += -DOPLUS_FEATURE_TP_BASIC

KBUILD_CFLAGS += -DOPLUS_FEATURE_MM_FEEDBACK
